### ISSUE TITLE
Issue to trigger new releases

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/ScientificTypesBase.jl#6]
@Juliaregistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

release notes:

- [x] Make all scitypes abstract where possible (#13)

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

release notes:

- [x] (**enhancement**) Add `Sampleable{K}` and `Density{K} <: Sampleable{K}` scientific types. Here `K` is the scientific type of the sample space (#15)

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

release notes:

- [x] Add the new scitype `Compositional{D} <: Known` for compositional data as provided by CoDa.jl (#20) @juliohm

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

release notes:

- (**breaking**)  #25

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- (**new feature**) Arrange for `scitype()` to print the active type hierarchy (#30)
